name: Draft New Release

on:
  push:
    branches:
      - main

permissions:
  contents: write     # needed to create/update releases
  id-token: write     # for semantic-release auth if required
  packages: write     # for any semantic-release plugins that touch packages

jobs:
  prepare-and-draft:
    runs-on: ubuntu-latest
    outputs:
      next_version: ${{ steps.bump.outputs.next_release_version }}

    steps:
      # 1. Check out your code
      - name: Checkout
        uses: actions/checkout@v3

      # 2. Determine next version (dry-run)
      - name: Determine next version
        id: bump
        uses: cycjimmy/semantic-release-action@v4
        with:
          dryRun: true
          extra_plugins: |
            @semantic-release/changelog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN:    ${{ secrets.NPM_TOKEN }}

      # 3. Create the draft pre-release with your exact template
      - name: Draft GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: v${{ needs.prepare-and-draft.outputs.next_version }}
          release_name: v${{ needs.prepare-and-draft.outputs.next_version }}
          draft: true
          prerelease: true
          body: |
            v${{ needs.prepare-and-draft.outputs.next_version }}
            **Triggered by committer:** @${{ github.actor }}
            ---
            # What's changed?
            ${{ github.event.head_commit.message }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
