name: Release Package

on:
  release:
    types: [published, prereleased]

permissions:
  contents: read
  packages: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./package

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.3.1

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23.7.0'

      - name: Install npm dependencies
        run: npm install
        working-directory: ./

      - name: Build all platforms
        run: npm run build:all
        working-directory: ./

      - name: Publish to npmjs.org
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish to GitHub Packages
        run: npm publish --registry https://npm.pkg.github.com
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
